language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
before_install:
  - 'cpanm Crypt::CBC'
  - 'cpanm Crypt::Rijndael'
  - 'cpanm Carp'
  - 'cpanm Moo'
  - 'cpanm Test::Most'
  - 'cpanm Try::Tiny'
  - 'cpanm YAML::XS'
  - 'cpanm JSON'
  - 'cpanm Devel::Cover::Report::Coveralls'
script:
  perl Makefile.PL && make test && cover -test -report coveralls
